# Generated by Django 4.0.4 on 2022-05-12 18:46

import dashboard.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_post_post_content_alter_replie_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to='', validators=[dashboard.validators.validate_file]),
        ),
    ]
