# Generated by Django 4.0.4 on 2022-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_upload_notes_notesfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
