# Generated by Django 4.0.4 on 2022-05-13 03:38

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_upload_notes_notesfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_notes',
            name='notesfile',
            field=models.FileField(null=True, upload_to='', validators=[dashboard.models.validate_file_extension]),
        ),
    ]
