# Generated by Django 4.0.4 on 2022-05-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_upload_notes_notesfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='replie',
            name='reply_content',
            field=models.CharField(max_length=5000),
        ),
    ]
