# Generated by Django 4.0.4 on 2022-05-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_post_post_content_alter_replie_reply_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.TextField(max_length=5000, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='replie',
            name='reply_content',
            field=models.TextField(max_length=5000, verbose_name=''),
        ),
    ]
