# Generated by Django 4.0.4 on 2022-05-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_post_post_content_alter_replie_reply_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='branch',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
