# Generated by Django 4.0.4 on 2022-05-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_post_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='branch',
            field=models.CharField(default='', max_length=200),
        ),
    ]
