# Generated by Django 4.0.4 on 2022-06-10 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
