# Generated by Django 4.0.4 on 2022-06-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='branch',
        ),
    ]
